# Generated by Django 3.1.2 on 2020-11-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201116_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='problem',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
