# Generated by Django 3.1.2 on 2020-11-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201116_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='prob_id',
            field=models.CharField(max_length=100),
        ),
    ]
