# Generated by Django 3.1.2 on 2020-11-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201116_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.CharField(max_length=500),
        ),
    ]
